// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/elastic/go-elasticsearch/v8"
	"github.com/go-playground/validator/v10"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"go-standard/internal/config"
	"go-standard/internal/handler"
	"go-standard/internal/infrastructure"
	"go-standard/internal/pkg/jwt"
	"go-standard/internal/task/email"
	"go-standard/internal/task/notification"
	"go-standard/internal/task/payment"
	"go-standard/internal/worker"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp is the Wire injector. Wire generates the body in wire_gen.go.
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	db, cleanup, err := infrastructure.NewPostgresDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := infrastructure.NewRedisClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	elasticsearchClient, cleanup3, err := infrastructure.NewElasticClient(cfg)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	logger, cleanup4, err := infrastructure.NewLogger(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	manager, err := jwt.NewManager(cfg)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := ProvideErrorHandler()
	requestIDMiddleware := ProvideRequestIDMiddleware()
	loggerMiddleware := ProvideLoggerMiddleware(logger)
	recoverMiddleware := ProvideRecoverMiddleware(logger)
	corsMiddleware := ProvideCORSMiddleware()
	defaultRateLimiter := ProvideDefaultRateLimiter(client, cfg)
	authRateLimiter := ProvideAuthRateLimiter(client, cfg)
	authMiddleware := ProvideAuthMiddleware(manager)
	validate := ProvideValidator()
	userRepository := ProvideUserRepository(db, logger)
	userUsecase := ProvideUserUsecase(db, userRepository, client, elasticsearchClient, manager, logger)
	userHandler := ProvideUserHandler(userUsecase, validate)
	authUsecase := ProvideAuthUsecase(db, userRepository, client, elasticsearchClient, manager, logger)
	authHandler := ProvideAuthHandler(authUsecase, validate)
	app := &App{
		Config:         cfg,
		DB:             db,
		Redis:          client,
		ES:             elasticsearchClient,
		Logger:         logger,
		JWTManager:     manager,
		ErrorHandler:   v,
		RequestID:      requestIDMiddleware,
		LoggerMW:       loggerMiddleware,
		Recover:        recoverMiddleware,
		CORS:           corsMiddleware,
		DefaultLimiter: defaultRateLimiter,
		AuthLimiter:    authRateLimiter,
		AuthMW:         authMiddleware,
		Validator:      validate,
		UserHandler:    userHandler,
		AuthHandler:    authHandler,
	}
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// InitializeWorker builds the worker binary's dependency graph.
// Shares InfraSet with the API binary — no duplication of infra wiring.
func InitializeWorker(cfg *config.Config) (*worker.Server, func(), error) {
	client, cleanup, err := infrastructure.NewRedisClient(cfg)
	if err != nil {
		return nil, nil, err
	}
	logger, cleanup2, err := infrastructure.NewLogger(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	emailHandler := email.NewEmailHandler(logger)
	paymentHandler := payment.NewPaymentHandler(logger)
	notificationHandler := notification.NewNotificationHandler(logger)
	serveMux := worker.NewServeMux(logger, emailHandler, paymentHandler, notificationHandler)
	server, cleanup3, err := worker.NewServer(cfg, client, serveMux, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// App holds all wired dependencies needed to start the server.
type App struct {
	Config         *config.Config
	DB             *gorm.DB
	Redis          *redis.Client
	ES             *elasticsearch.Client
	Logger         *zap.Logger
	JWTManager     *jwt.Manager
	ErrorHandler   fiber.ErrorHandler
	RequestID      RequestIDMiddleware
	LoggerMW       LoggerMiddleware
	Recover        RecoverMiddleware
	CORS           CORSMiddleware
	DefaultLimiter DefaultRateLimiter
	AuthLimiter    AuthRateLimiter
	AuthMW         AuthMiddleware
	Validator      *validator.Validate
	UserHandler    *handler.UserHandler
	AuthHandler    *handler.AuthHandler
}

// InfraSet wires all infrastructure dependencies.
var InfraSet = wire.NewSet(infrastructure.NewLogger, infrastructure.NewPostgresDB, infrastructure.NewRedisClient, infrastructure.NewElasticClient)

// MiddlewareSet wires the JWT manager and all middleware handlers.
var MiddlewareSet = wire.NewSet(jwt.NewManager, ProvideErrorHandler,
	ProvideRequestIDMiddleware,
	ProvideLoggerMiddleware,
	ProvideRecoverMiddleware,
	ProvideCORSMiddleware,
	ProvideDefaultRateLimiter,
	ProvideAuthRateLimiter,
	ProvideAuthMiddleware,
)
